security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:1100/auth/oauth/token
      userAuthorizationUri: http://localhost:1100/auth/oauth/authorize
      grant-type: password
    resource:
      userInfoUri: http://localhost:1100/auth/user/me
      preferTokenInfo: true
      jwt:
        key-uri: http://localhost:1100/auth/oauth/token_key


